### ISSUE TITLE
MKS GEN L cable connectors typ?

### ISSUE THREAD

**Issue by LuckyLuzz** [makerbase-mks/Datasheet#3]
Hello,
I just bought a MKS GEN L Board and was wondering what kind of connector typ it is you guys used for the stepper, endstop and temp connection. I couldn't find it online. 

I need that info so I can convert my Vertex K8400 to the new Motherboard.

Thanks :)

**Comment by theopensourcerer** [comment]
On the picture on the datasheet they look like JST XH connectors.

**Comment by LuckyLuzz** [comment]
Thanks :)

**Comment by Cheesecheesy** [comment]
Hi, just want to ask, it it possible to use the original optical endstop and attach to MKS gen L ?
