### ISSUE TITLE
A6 LCD12864 & MKS GEN L 1.0

### ISSUE THREAD

**Issue by RcTomcat1** [makerbase-mks/Datasheet#5]
I can't seem to get the Anet A6 LCD12864 to work on my MKS Gen L 1.0. It just glows without showing any text.
[3D Drucker.zip](https://github.com/makerbase-mks/Datasheet/files/2668488/3D.Drucker.zip)

The Anet Display is enabled in the config file. The Display works fine on the original Anet Motherboard and my marlin firmware.  I changed the motherboard in the config file from the anet to the mks of course but that did not solve my problem.
I tried adjusting the pins in the pins_MKS_Gen_L.h but it keeps glowing without text.

My config.h and the pins.h including some pics of the cabling are attached in the zip archive.
Any help is greatly appreciated.

**Comment by RcTomcat1** [comment]
Fixed it myself, found the correct pinout

**Comment by asorie** [comment]
Could you please provide the pinout?
